apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud
      containers:
      - name: nextcloud
        image: nextcloud
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: nextcloud
        env:
        - name: TRUSTED_PROXIES
          value: 192.168.1.2
        - name: OVERWRITEPROTOCOL
          value: https

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
  - port: 80
  selector:
    app: nextcloud
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx/client_max_body_size: 5g
spec:
  tls:
  - hosts:
    - nextcloud.example.com
    secretName: nextcloud
  rules:
  - host: nextcloud.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
